apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: node-class
spec:

  role: "AmazonEKSAutoNodeRole"
  # Automatically tells EKS Auto Mode to locate your VPC subnets
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/internal-elb: "1"
  
  # Hooks your EC2 nodes up to the default cluster security group
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/ecommerce-app-eks: "owned" # Ensure 'example' matches your actual EKS cluster name