apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-pool
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: node-class
      requirements:
        # Limit server generation to the budget-friendly t3 or t3a families
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3", "t3a"]
        
        # Lock size to 'medium' (the absolute smallest permitted size for EKS Auto Mode)
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["micro"]

        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
  limits:
    cpu: "4"
    memory: 8Gi