kind: Deployment
apiVersion: apps/v1
metadata:
  name: ecommerce-app-frontend-deployment
  labels:
    app: ecommerce-app-frontend
  namespace: ecommerce-app-ns
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ecommerce-app-frontend
  template:
    metadata:
      labels: 
        app: ecommerce-app-frontend
    spec:
      containers:
        - name: ecommerce-app-frontend
          image: samarthlambture/ecommerce-store_frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DANGEROUSLY_DISABLE_HOST_CHECK
              value: "true"
          stdin: true
          tty: true

---
kind: Deployment
apiVersion: apps/v1 
metadata:
  name: ecommerce-app-backend-deployment
  labels:
    app: ecommerce-app-backend
  namespace: ecommerce-app-ns
spec:
  serviceAccountName: backend-sa  # new SA with IRSA annotation
  replicas: 1
  selector:
    matchLabels: 
      app: ecommerce-app-backend
  template:
    metadata:
      labels: 
        app: ecommerce-app-backend
    spec:
      containers:
        - name: ecommerce-app-backend
          image: samarthlambture/ecommerce-store_backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_CONNECTION
              value: "mongodb://ecommerce-app-database-service:27017/ecommerce"
            
            # --- ADD THESE FOR YOUR SQS LOGIC ---
            - name: AWS_REGION
              value: "ap-south-2"
            
            - name: SQS_QUEUE_URL
              # Use the exact output URL generated by your Terraform run
              value: "https://sqs.ap-south-2.amazonaws.com/622915751178/ecommerce-orders-queue"

---
kind: Deployment
apiVersion: apps/v1 
metadata:
  name: ecommerce-app-database-deployment
  labels:
    app: ecommerce-app-database
  namespace: ecommerce-app-ns
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ecommerce-app-database
  template:
    metadata:
      labels: # FIXED: changed from label
        app: ecommerce-app-database
    spec:
      containers:
        - name: ecommerce-app-database
          image: mongo:6.0
          ports:
            - containerPort: 27017