apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-service-scaler
  namespace: ecommerce-app-ns 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecommerce-app-backend-deployment 
  
  minReplicaCount: 0  
  maxReplicaCount: 10 
  pollingInterval: 15 
  cooldownPeriod:  300 

  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-aws-credentials 
      metadata:
        queueURL: https://sqs.ap-south-2.amazonaws.com/622915751178/ecommerce-orders-queue
        queueLength: "10" 
        awsRegion: ap-south-2