apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-quick-tunnel
  namespace: ecommerce-app-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-quick-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-quick-tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --url
        - http://ecommerce-app-frontend-service.ecommerce-app-ns.svc.cluster.local:80