kind: Service
apiVersion: v1
metadata:
  name: ecommerce-app-frontend-service
  namespace: ecommerce-app-ns
  labels:
    app: ecommerce-app-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-inbound-cidrs: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP" 
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"  
spec:
  selector:
    app: ecommerce-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: ecommerce-app-backend-service
  namespace: ecommerce-app-ns
  labels:
    app: ecommerce-app-backend    
spec:
  selector:
    app: ecommerce-app-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: ecommerce-app-database-service
  namespace: ecommerce-app-ns
  labels:
    app: ecommerce-app-database
spec:
  selector:
    app: ecommerce-app-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP